apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
data:
  DJANGO_SETTINGS_MODULE: "app.settings"
  # add other config values if needed

