{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "django-app.fullname" . }}-rules
  namespace: {{ .Values.global.namespace }}
spec:
  groups:
    - name: django.rules
      rules:
        - alert: DjangoDown
          expr: up == 0
          for: 1m
          labels:
            severity: critical
{{- end }}
