apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{- include "django-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.serviceType | default "ClusterIP" }}
  selector:
{{- include "django-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}

