apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "django-app.name" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.app.port }}
      name: http
